export const NEXT_PUBLIC_API_URL = process.env.NEXT_PUBLIC_API_URL;
export const NEXT_PUBLIC_AUTH_API_URL = process.env.NEXT_PUBLIC_AUTH_API_URL;
export const NEXT_PUBLIC_WS_URL = process.env.NEXT_PUBLIC_WS_URL;
export const NEXT_PUBLIC_FACEBOOK_APP_ID =
  process.env.NEXT_PUBLIC_FACEBOOK_APP_ID;
export const NEXT_PUBLIC_ZALO_APP_ID = process.env.NEXT_PUBLIC_ZALO_APP_ID;
export const NEXT_PUBLIC_ZALO_APP_SECRET =
  process.env.NEXT_PUBLIC_ZALO_APP_SECRET;
// Firebase
export const NEXT_PUBLIC_FIREBASE_API_KEY =
  process.env.NEXT_PUBLIC_FIREBASE_API_KEY;
export const NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN =
  process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN;
export const NEXT_PUBLIC_FIREBASE_PROJECT_ID =
  process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID;
export const NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET =
  process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET;
export const NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID =
  process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID;
export const NEXT_PUBLIC_FIREBASE_APP_ID =
  process.env.NEXT_PUBLIC_FIREBASE_APP_ID;
export const NEXT_PUBLIC_VAPID_KEY = process.env.NEXT_PUBLIC_VAPIDKEY;

export const NEXT_PUBLIC_WHATSAPP_APP_ID =
  process.env.NEXT_PUBLIC_WHATSAPP_APP_ID;

export const NEXT_PUBLIC_SERVER_CALLBACK_URL_ZALO =
  process.env.NEXT_PUBLIC_SERVER_CALLBACK_URL_ZALO;
